# relay pagination
type PageInfo {
    startCursor: String
    endCursor: String
    hasNextPage: Boolean!
    hasPreviousPage: Boolean!
}

# ###################################################################
# Prices - Associated with a product
# ###################################################################


input PricesInput {
    first: Int = 10
    after: String
}

type Price {
    id: ID!
    currency: String!
    type: String!
    interval: String
    amount: Int!
    formattedAmount: String!
}

type PriceEdge {
    cursor: String!
    node: Price!
}

type PricesConnection {
    pageInfo: PageInfo!
    edges: [PriceEdge!]!
}

# ###################################################################
# Products - What you sell; both physical and digial
# ###################################################################

input SearchProductsInput {
    first: Int = 10
    after: String
}

type Product {
    id: String!
    name: String!
    description: String!
    images: [String!]!
    shippable: Boolean
    prices(input: PricesInput): PricesConnection!
}

type SearchProductsEdge {
    cursor: String!
    node: Product!
}

type SerachProductsConnection {
    pageInfo: PageInfo!
    edges: [SearchProductsEdge!]!
}

# ###################################################################
# Queries & Mutations
# ###################################################################

type Query {
    "Stripe Products (used for physical products and subscriptions)"
    searchProducts(input: SearchProductsInput): SerachProductsConnection!
}
