service: '${self:custom.vars.SERVICE_NAME}'

app: ftf

plugins:
  - serverless-prune-plugin

custom:
  vars:
    # general
    SERVICE_NAME: stripe-service 
    RESOURCE_NAMESPACE: '${self:app}-${opt:stage}-${self:service}'
    SSM_NAMESPACE: '/${self:app}/${opt:stage}/${self:service}'

    # node
    NODE_ENV: '${ssm:/${self:app}/${opt:stage}/infra/node-env}'
    NODE_VERSION: 'nodejs14.x'

    # stripe
    STRIPE_API_KEY: '${ssm:/${self:app}/${opt:stage}/stripe/api-key}'
    STRIPE_SIGNING_SECRET: '${ssm:/${self:app}/${opt:stage}/stripe/signing-secret}'

  prune:
    automatic: true
    number: 3

provider:
  name: aws

  runtime: '${self:custom.vars.NODE_VERSION}'
  timeout: 6
  stackName: '${self:custom.vars.RESOURCE_NAMESPACE}'

  environment:
    NODE_ENV: '${self:custom.vars.NODE_ENV}' 
    STRIPE_API_KEY: '${self:custom.vars.STRIPE_API_KEY}'
    
functions:

  private:
    name: '${self:custom.vars.RESOURCE_NAMESPACE}-private-subgraph'
    handler: lambda.handler
    enviornment:
      SECURITY: private

  public:
    name: '${self:custom.vars.RESOURCE_NAMESPACE}-public-subgraph'
    handler: lambda.handler
    enviornment:
      SECURITY: public

  webhooks:
    name: '${self:custom.vars.RESOURCE_NAMESPACE}-webhooks'
    handler: webhooks/index.handler
    environment:
      STRIPE_SIGNING_SECRET: <>
