version: 2.1

orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.3
  jq: circleci/jq@2.2.0

jobs:

  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages

  lint:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:cover
  
  publish-subgraph:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Publish Subgraph Schema
          command: |
            APOLLO_GRAPH_ID=ftf-main-private \
            APOLLO_GRAPH_VARIANT=ftf-main-private \
            npx rover subgraph publish "$APOLLO_GRAPH_ID@$APOLLO_GRAPH_VERSION" \
              --name stripe \
              --schema ./private-schema.gql

  deploy: 
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npx serverless deploy --stage ${CIRCLE_BRANCH}

  # integration:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - run: npm run integration

workflows:
  version: 2
  primary:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          context: FTF 
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - main
      - publish-subgraph:
          context: FTF 
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - main
      # - integration:
      #     context: FTF
      #     requires:
      #       - api-deploy 
      #     filters:
      #       branches:
      #         only:
      #           - main